### ISSUE TITLE
What about octave?

### ISSUE THREAD

**Issue by stefano2734** [vishalk2/Numerical-Techniques-Fluid-Mechanics-and-CFD#1]
Compatible to free matlab clone octave?
No license is needed for octave.

If yes, please extend your info.
if unknown, untested with octave is also nice.
if no, it is also ok. Some commands are not compatible in octave.

**Comment by vishalk2** [comment]
I've never tested the codes through Octave. With whatever little I know, the code should more or less work on Octave except for raising errors here and there. You can try them if you are interested. Thanks for your comment. :)

**Comment by stefano2734** [comment]
What do you think about octave as expert of your software?
https://wiki.octave.org/Differences_between_Octave_and_Matlab
https://wiki.octave.org/Release_History
https://octave.org/NEWS-7.html
